# Generated by Django 5.2 on 2025-11-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_member_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_added',
        ),
    ]
