# Generated by Django 5.2 on 2025-11-21 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Employee Info', 'verbose_name_plural': 'Employee Info'},
        ),
        migrations.AddField(
            model_name='customer',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
