# Generated by Django 5.2 on 2025-10-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_salesreport_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='P0', max_length=10, unique=True),
        ),
    ]
