# Generated by Django 5.2 on 2025-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_stock',
            field=models.IntegerField(default=0),
        ),
    ]
