# Generated by Django 5.2 on 2025-12-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_product_original_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('satisfaction', models.IntegerField(blank=True, choices=[(1, 'Very Unsatisfied'), (2, 'Unsatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('new', 'New Customer'), ('returning', 'Returning Customer'), ('business', 'Business Client'), ('student', 'Student'), ('other', 'Other')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
