# Generated by Django 5.2.1 on 2025-10-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_delete_viewonlygroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='employee_name',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_name',
            new_name='customer_id',
        ),
    ]
